name: Deploy MultiDocker
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - run: docker build -t elemnt17/react-test -f ./client/Dockerfile.dev ./client
            - run: docker run -e CI=true elemnt17/react-test npm test

            - run: docker build -t elemnt17/multi-client ./client
            - run: docker build -t elemnt17/multi-nginx ./nginx
            - run: docker build -t elemnt17/multi-server ./server
            - run: docker build -t elemnt17/multi-worker ./worker

            - run: docker push elemnt17/multi-client
            - run: docker push elemnt17/multi-nginx
            - run: docker push elemnt17/multi-server
            - run: docker push elemnt17/multi-worker

            - name: Generate deployment package
              run: zip -r deploy.zip . -x '*.git*'

            - name: Deploy to EB
              uses: einaregilsson/beanstalk-deploy@v18
              with:
                  aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
                  aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
                  application_name: multicontainer-docker
                  environment_name: Multicontainerdocker-env-1
                  existing_bucket_name: elasticbeanstalk-ap-northeast-1-017508380662
                  region: ap-northeast-1
                  version_label: ${{ github.sha }}
                  deployment_package: deploy.zip
